apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: backend-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: first-backend:latest
        ports:
        - containerPort: 9090
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: flask-secrete
                key: DB_USERNAME
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: DB_NAME
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: flask-secrete
                key: DB_PORT
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: flask-secrete
                key: DB_PASSWORD